#
# Install Cassandra cluster on Centos
# C* 2.1.9 / Centos 6.6
#
#

- name: Cassandra install
  hosts: datastax-all
  user: root
  roles:
    - common
    - dns
    - java
    - datastax-yum-repo
    - dsc-cassandra
    - datastax-agent



  tasks:
  - name: Restart agent
    service: name=datastax-agent state=restarted        