#
# Install DSE cluster on Centos
# DSE 4.8.0 / Centos 6.6
#

- name: DSE install
  hosts: datastax-all
  user: root
  roles:
    ##- cassandra-cleandata
    - common
    - dns
    - java
    - datastax-yum-repo
    - dse
    - datastax-agent

  tasks:
  - name: Restart agent
    service: name=datastax-agent state=restarted

